### ISSUE TITLE
数据结构》树：find方法没有做防御性编程，导致传入数值找不到时报错

### ISSUE THREAD

**Issue by Lucien-X** [HcySunYang/knowledge#4]
修改后相关代码如下,在移动current到左右节点之前先判断左右节点是否存在，不存在就直接跳出：
```javascript
        // 查找指定值
	find:function(data){
		var current=this.root;
		while(true){
			if(data==current.data){
				return current;
			}
			if(data<current.data){
				if(current.left){
					current=current.left;
				}else{
					break;
				}
			}
			if(data>current.data){
				if(current.right){
					current=current.right;
				}else{
					break;
				}
			}
		}
		return null;
	}
```

另外，英文拼写有误，先序(根)遍历是preOrder traversal，不是perOrder。
还有，除先序遍历，中序遍历，后序遍历以外，
还有按层遍历，按层遍历由于存在先入先出的特性，正好可以利用到之前队列的结构，望补充

**Comment by HcySunYang** [comment]
@Lucien-X 首先，感谢你的纠正。拼写错误已经修改。
然后你对 find 方法的改进体现了你对待问题的严谨性，这应该是一个程序员应该有的特质。本例中的 find 方法摘自 《数据结构与算法 JavaScript 描述》一书，论严谨，书中的例子有很多都是不严谨的地方，但这并不妨碍它教会我们思路，正如当你看到这个 find 方法的时候所提出的这些问题，我想当你将这些数据结构应用到具体的项目中时，或许除了思路对我们是有用的，里面的逻辑都要根据具体的项目进行相应的修改，比如各种边界情况的判断。所以我没有修改例子中的 find 方法，希望你能明白我的意思。
关于树的按层遍历，实际上在二叉树中是应用的不多的，特别是特殊的二叉树，比如二叉查找树(排序树)，所以这里并没有介绍，而在介绍图的时候，其广度优先搜索即是按层遍历的例子，我想思路也是一样，不过我倒是可以考虑加进来。
最后再次感谢你所提出的问题。

**Comment by Lucien-X** [comment]
首先还是十分感谢您所做的翻译和整理，图示很清晰，去看了下原书的PDF，错误太多导致无力吐槽了，才发现你能描述成这样已经实属不易。《数据结构与算法 JavaScript 描述》一书中确实有不少不严谨的地方，但是吸收其中思路还是很赞的。
还有，刚刚还发现了，二叉搜索树中的key应该都是唯一的，但是算法中使用else覆盖了大于和等于的情况，导致重复节点会添加到右子树。
```javascript
insert:function(data){
		// 1、根据输入的数据 data 创建一个新的节点。
		var n=new Node(data);
		// 2、检查是否有根节点，如果没有根节点证明这是一颗新树，将该节点作为根节点。
		if(!this.root){
			this.root=n;
			return;
		}
		// 3、否则，开始遍历树，将根节点设为当前节点，使用新节点与当前节点作比较，
		// 如果新节点的值小于当前节点:
		// 3.1、如果当前节点的左子节点为null，则将新节点设为当前节点的左子节点，退出循环。
		// 3.2、如果当前节点的左子节点不为null，则更新当前节点为当前节点的左子节点，执行下一次循环。
		var current=this.root;
		while(true){
			if(data<current.data){
				if(!current.left){
					current.left=n;
					break;
				}
				current=current.left;
			}
			if(data>current.data){
				if(!current.right){
					current.right=n;
					break;
				}
				current=current.right;
			}
			// 由于二叉树定义中，每个结点都有一个作为搜索依据的关键码(key)，
			// 所有结点的关键码互不相同。
			// 当插入值已存在，不再重复插入
			if(data==current.data){
				break;
			}
		}
	},
```
